<?php echo $this->doctype(); ?>
<html lang="is">
    <head>
		<meta charset="utf-8">
		<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>
		<meta name="msapplication-TileColor" content="#292468">
		<meta name="msapplication-TileImage" content="<?=$this->basePath("favicons/mstile-144x144.png");?>">
		<meta name="theme-color" content="#292468">

        <?=$this->headTitle('FlightInfo ')->setSeparator(' / ')->setAutoEscape(false) ?>
		<?=$this->headScript();?>
        <?=$this->headLink(); ?>

    </head>
	<body>
		<?=$this->content; ?>
		<?=$this->inlineScript() ?>
	</body>
</html>
